"""
Seed db/dpdpa.db with the full Digital Personal Data Protection Act, 2023
— all 44 sections + the penalty Schedule.

Sources:
1. Act text (full_text): loaded from data/act_verbatim_2026-09-23.json,
   which scripts/rebuild_act_verbatim_2026-09-23.py generated by extracting
   the text mechanically, word for word, from the official Act PDF
   (docs/full_text/DPDP_Act_2023_official_2026-09-23.pdf) — see that
   script and docs/act_verbatim_rebuild_2026-09-23.md for how it was built
   and checked. Nothing in PROVISIONS below is the source of the clause
   text; only reference/topic/summary/effective-date metadata lives here.
2. Commencement dates: Gazette Notification G.S.R. 843(E), dated 13 Nov 2025
   (Ministry of Electronics and Information Technology), supplied by the
   user as an uploaded PDF (Timelines_for_enforcement_of_DPDPA.pdf).

Section 6 and Section 27 are each split into two rows because a specific
sub-clause of each commences on a different date than the rest of the
section (mirrors how Rule 8 was split in seed_dpdp_rules_full.py).

Usage:
    python src/init_db.py                 # schema only, if not already done
    python src/seed_dpdp_rules_full.py    # if not already run
    python src/seed_dpdp_act_full.py
    python src/export_word.py
    python src/export_excel.py
"""
from __future__ import annotations

import json
import re

from db import PROJECT_ROOT, get_connection, init_schema

VERBATIM_JSON_PATH = PROJECT_ROOT / "data" / "act_verbatim_2026-09-23.json"


def load_verbatim_full_text() -> dict[str, str]:
    """provision_id -> full_text, code-extracted from the official Act PDF
    (see VERBATIM_JSON_PATH's own header for the PDF hash and extractor
    versions used)."""
    data = json.loads(VERBATIM_JSON_PATH.read_text(encoding="utf-8"))
    return {pid: entry["full_text"] for pid, entry in data["provisions"].items()}

DOCX_PATH = "docs/DPDP_Act_2023.docx"

ACT_SOURCE_DOC = "Digital Personal Data Protection Act, 2023 (Act No. 22 of 2023)"
ACT_SOURCE_URL = "https://www.meity.gov.in/static/uploads/2024/06/2bf1f0e9f04e6fb4f8fef35e82c42aa5.pdf"
COMMENCEMENT_SOURCE_DOC = "Gazette Notification G.S.R. 843(E), 13 Nov 2025 (Act commencement schedule)"
COMMENCEMENT_SOURCE_URL = "user-upload:Timelines_for_enforcement_of_DPDPA.pdf"
FETCHED_DATE = "2026-08-31"

EFF_GROUP_A = ("2025-11-13", "In force from date of notification (G.S.R. 843(E), group (a)).")
EFF_GROUP_B = ("2026-11-13", "In force one year after notification (G.S.R. 843(E), group (b)).")
EFF_GROUP_C = ("2027-05-13", "In force eighteen months after notification (G.S.R. 843(E), group (c)) — not yet operative.")

# (provision_id, reference, topic, summary, effective_group) --
# full_text is looked up separately from data/act_verbatim_2026-09-23.json.
PROVISIONS = [
    ("DPDPA-S1", "Section 1", "Other",
     "Short title of the Act and the commencement mechanism — different provisions can be brought into force on different notified dates, as happened via G.S.R. 843(E).",
     EFF_GROUP_A),

    ("DPDPA-S2", "Section 2", "Definitions",
     "Defines the Act's core terms — Data Fiduciary, Data Principal, Data Processor, Significant Data Fiduciary, personal data, processing, personal data breach, consent manager, Board, and more.",
     EFF_GROUP_A),

    ("DPDPA-S3", "Section 3", "Other",
     "Defines the territorial and material scope of the Act — applies to digital personal data processed in India, and to processing outside India connected to offering goods/services to people in India. Excludes purely personal/domestic processing and data the individual has made publicly available herself.",
     EFF_GROUP_C),

    ("DPDPA-S4", "Section 4", "Consent & Notice",
     "Personal data may only be processed for a lawful purpose (not expressly forbidden by law) where the Data Principal has given consent, or where one of the Act's 'certain legitimate uses' (Section 7) applies.",
     EFF_GROUP_C),

    ("DPDPA-S5", "Section 5", "Consent & Notice",
     "Requires a notice (describing the personal data, purpose, and how to exercise rights or complain to the Board) to accompany or precede every consent request, and separately requires retrospective notice to people who consented before the Act's commencement.",
     EFF_GROUP_C),

    ("DPDPA-S6.1_8_10", "Section 6(1)-(8),(10)", "Consent & Notice",
     "Sets the standard for valid consent (free, specific, informed, unconditional, unambiguous, purpose-limited), the right to withdraw it at any time as easily as it was given, the consequences of withdrawal, and the Data Fiduciary's burden of proving valid notice/consent in any proceeding.",
     EFF_GROUP_C),

    ("DPDPA-S6.9", "Section 6(9)", "Consent Manager",
     "Every Consent Manager must be registered with the Board, subject to prescribed technical, operational, and financial conditions. (This sub-clause commences a year after the rest of Section 6, alongside Rule 4's registration process.)",
     EFF_GROUP_B),

    ("DPDPA-S7", "Section 7", "Other",
     "Lists nine 'certain legitimate uses' that permit processing without consent — voluntary data-sharing for an obvious purpose, State benefit delivery, State legal functions, legal disclosure obligations, court orders, medical emergencies, public health measures, disaster response, and employment-related purposes.",
     EFF_GROUP_C),

    ("DPDPA-S8", "Section 8", "Other",
     "Sets the Data Fiduciary's general obligations — responsibility regardless of contracts/Data Principal default, contractual requirement for engaging Data Processors, accuracy where decisions/disclosure are involved, security safeguards, breach intimation to the Board and Data Principals, erasure once purpose is no longer served, DPO/contact publication, and grievance redressal.",
     EFF_GROUP_C),

    ("DPDPA-S9", "Section 9", "Children & Persons with Disabilities",
     "Requires verifiable parental/guardian consent before processing a child's (or disabled person's, where under lawful guardianship) personal data, bars processing likely to harm a child's wellbeing, and bars tracking/behavioural monitoring/targeted advertising directed at children — subject to prescribed exemptions and an age-based safe-harbour the government can notify.",
     EFF_GROUP_C),

    ("DPDPA-S10", "Section 10", "Significant Data Fiduciary",
     "Empowers the government to designate Significant Data Fiduciaries based on data volume/sensitivity, rights risk, and sovereignty/security/electoral/public-order impact; requires them to appoint an India-based Data Protection Officer, an independent data auditor, and undertake periodic Data Protection Impact Assessments and audits.",
     EFF_GROUP_C),

    ("DPDPA-S11", "Section 11", "Data Principal Rights",
     "Gives a Data Principal the right to obtain a summary of her personal data being processed, the identities of other Data Fiduciaries/Processors it's been shared with, and other prescribed information — subject to a law-enforcement disclosure carve-out.",
     EFF_GROUP_C),

    ("DPDPA-S12", "Section 12", "Data Principal Rights",
     "Gives a Data Principal the right to correction, completion, updating, and erasure of her personal data (subject to legal retention requirements) for processing she previously consented to.",
     EFF_GROUP_C),

    ("DPDPA-S13", "Section 13", "Data Principal Rights",
     "Gives a Data Principal the right to readily available grievance redressal from the Data Fiduciary/Consent Manager, with a prescribed response period, and requires her to exhaust that route before approaching the Board.",
     EFF_GROUP_C),

    ("DPDPA-S14", "Section 14", "Data Principal Rights",
     "Gives a Data Principal the right to nominate another individual to exercise her rights in the event of her death or incapacity.",
     EFF_GROUP_C),

    ("DPDPA-S15", "Section 15", "Data Principal Rights",
     "Sets five duties on Data Principals — comply with applicable law, don't impersonate others, don't suppress material information on official documents, don't file false/frivolous grievances, and provide only verifiably authentic information when seeking correction/erasure.",
     EFF_GROUP_C),

    ("DPDPA-S16", "Section 16", "Cross-Border Transfer",
     "Allows the government to restrict transfer of personal data to specific notified countries/territories, without displacing any other law that provides stronger cross-border protection.",
     EFF_GROUP_C),

    ("DPDPA-S17", "Section 17", "Exemptions",
     "Sets broad exemptions from most of the Act's obligations — for legal-right enforcement, judicial/regulatory processing, crime prevention/investigation, foreign-contract processing of non-Indian data, M&A restructuring, and defaulter financial-information processing — plus government-notified exemptions for security instrumentalities, research/statistics, and startups.",
     EFF_GROUP_C),

    ("DPDPA-S18", "Section 18", "Data Protection Board",
     "Establishes the Data Protection Board of India as a body corporate with perpetual succession, able to hold property and sue/be sued.",
     EFF_GROUP_A),

    ("DPDPA-S19", "Section 19", "Data Protection Board",
     "Sets the Board's composition (Chairperson + Members) and the qualification standard — ability, integrity, standing, and relevant expertise, with at least one legal expert.",
     EFF_GROUP_A),

    ("DPDPA-S20", "Section 20", "Data Protection Board",
     "Sets Chairperson/Member salary and terms (prescribed by Rules — see Fifth Schedule) and a two-year, renewable term of office.",
     EFF_GROUP_A),

    ("DPDPA-S21", "Section 21", "Data Protection Board",
     "Lists disqualifications for Board appointment/continuation — insolvency, moral-turpitude conviction, incapacity, conflicting financial interest, or position abuse — and requires a hearing before removal.",
     EFF_GROUP_A),

    ("DPDPA-S22", "Section 22", "Data Protection Board",
     "Sets the resignation process (effective on Government permission, three months' notice, successor appointment, or term expiry — whichever is earliest), vacancy-filling, and a one-year post-office employment restriction.",
     EFF_GROUP_A),

    ("DPDPA-S23", "Section 23", "Data Protection Board",
     "Sets the Board's meeting/authentication procedure (prescribed by Rules — see Rule 19), and a savings clause protecting Board acts from invalidation due to vacancies, appointment defects, or non-material procedural irregularities.",
     EFF_GROUP_A),

    ("DPDPA-S24", "Section 24", "Data Protection Board",
     "Allows the Board, with prior Central Government approval, to appoint officers/employees necessary for its functions, on prescribed terms.",
     EFF_GROUP_A),

    ("DPDPA-S25", "Section 25", "Data Protection Board",
     "Deems the Chairperson, Members, officers, and employees of the Board to be public servants under the Indian Penal Code while acting under the Act.",
     EFF_GROUP_A),

    ("DPDPA-S26", "Section 26", "Data Protection Board",
     "Gives the Chairperson general superintendence over Board administrative matters, and the power to delegate scrutiny/functions/proceedings to individual Members or groups of Members.",
     EFF_GROUP_A),

    ("DPDPA-S27.1a_c_e_2_3", "Section 27(1)(a)-(c),(e),(2),(3)", "Data Protection Board",
     "Sets most of the Board's core powers and functions — investigating breaches (on its own initiative, on complaints, or on government reference) and imposing penalties, issuing binding directions after a hearing, and modifying/withdrawing directions on representation.",
     EFF_GROUP_C),

    ("DPDPA-S27.1d", "Section 27(1)(d)", "Consent Manager",
     "Gives the Board the power to inquire into, and penalise, a breach of Consent Manager registration conditions. (Commences a year after the rest of Section 27, alongside Section 6(9)'s Consent Manager registration requirement.)",
     EFF_GROUP_B),

    ("DPDPA-S28", "Section 28", "Data Protection Board",
     "Sets the Board's inquiry procedure as an independent, digital-by-design body — determining if grounds exist to proceed, natural-justice-based inquiries, civil-court-equivalent evidentiary powers, and the ability to close/warn/cost frivolous complaints.",
     EFF_GROUP_C),

    ("DPDPA-S29", "Section 29", "Data Protection Board",
     "Sets the appeal process to the Appellate Tribunal (the TRAI Appellate Tribunal, per the Act's definitions) against a Board order — 60-day filing window, extendable for sufficient cause, a 6-month target disposal timeline, and digital-by-design functioning.",
     EFF_GROUP_C),

    ("DPDPA-S30", "Section 30", "Data Protection Board",
     "Makes Appellate Tribunal orders executable as a civil-court decree, either directly by the Tribunal or via transmission to a local civil court.",
     EFF_GROUP_C),

    ("DPDPA-S31", "Section 31", "Data Protection Board",
     "Allows the Board to direct parties toward mediation for disputes it considers suitable for that route.",
     EFF_GROUP_C),

    ("DPDPA-S32", "Section 32", "Data Protection Board",
     "Allows the Board to accept a voluntary undertaking from a person under inquiry (to take/refrain from action, or publicise the undertaking), which bars further proceedings on that matter unless the undertaking is later breached.",
     EFF_GROUP_C),

    ("DPDPA-S33", "Section 33", "Penalties",
     "Empowers the Board to impose the monetary penalties set out in the Schedule where it finds a significant breach, after a hearing, having regard to factors like breach severity, repetition, mitigation efforts, and proportionality.",
     EFF_GROUP_C),

    ("DPDPA-S34", "Section 34", "Penalties",
     "Requires all penalty sums realised by the Board to be credited to the Consolidated Fund of India.",
     EFF_GROUP_C),

    ("DPDPA-S35", "Section 35", "Other",
     "Shields the Central Government, Board, and Board personnel from legal proceedings for anything done in good faith under the Act or Rules.",
     EFF_GROUP_A),

    ("DPDPA-S36", "Section 36", "Other",
     "Empowers the Central Government to require the Board, or any Data Fiduciary/intermediary, to furnish information it calls for, for Act purposes.",
     EFF_GROUP_C),

    ("DPDPA-S37", "Section 37", "Other",
     "Empowers the Central Government to direct blocking of public access to a Data Fiduciary's online offering, after a hearing, where the Board has referred two or more monetary-penalty instances against that Data Fiduciary and recommends blocking in the public interest.",
     EFF_GROUP_C),

    ("DPDPA-S38", "Section 38", "Other",
     "Clarifies the Act operates in addition to (not instead of) other laws, but prevails over any conflicting provision to the extent of the conflict.",
     EFF_GROUP_A),

    ("DPDPA-S39", "Section 39", "Other",
     "Bars civil courts from hearing matters the Board is empowered to handle under the Act, and bars injunctions against actions taken under the Act's powers.",
     EFF_GROUP_A),

    ("DPDPA-S40", "Section 40", "Other",
     "The Central Government's rule-making power — this is the legal basis for the entire DPDP Rules, 2025, and lists 26 specific matters the Rules may cover.",
     EFF_GROUP_A),

    ("DPDPA-S41", "Section 41", "Other",
     "Requires every rule and certain notifications (under Sections 16 and 42) to be laid before both Houses of Parliament for a 30-day review period, during which Parliament can modify or annul them.",
     EFF_GROUP_A),

    ("DPDPA-S42", "Section 42", "Penalties",
     "Allows the Central Government to amend the penalty Schedule by notification, capped at no more than double the originally enacted penalty amounts; amendments take effect as if enacted, from the notification date.",
     EFF_GROUP_A),

    ("DPDPA-S43", "Section 43", "Other",
     "A standard 'removal of difficulties' clause — allows the government to make necessary orders to resolve implementation difficulties, but only within three years of the Act's commencement, and such orders must be laid before Parliament.",
     EFF_GROUP_A),

    ("DPDPA-S44.1_3", "Section 44(1),(3)", "Other",
     "Amends the TRAI Act, 1997 to fold in the DPDP Appellate Tribunal, and amends the RTI Act, 2005 to redefine what counts as exempt 'personal information' by reference to this Act.",
     EFF_GROUP_A),

    ("DPDPA-S44.2", "Section 44(2)", "Other",
     "Amends the Information Technology Act, 2000 — removes the old compensation-for-data-breach provision (Section 43A, since this Act now governs that), and cross-references this Act in two other IT Act provisions.",
     EFF_GROUP_C),

    ("DPDPA-SCHED", "Schedule (Act)", "Penalties",
     "Sets the monetary penalty ranges the Board can impose for different categories of breach — up to ₹250 crore for a security-safeguard breach, ₹200 crore for breach-notification or children's-data failures, ₹150 crore for Significant Data Fiduciary obligation breaches, and ₹50 crore for other breaches of the Act or Rules.",
     EFF_GROUP_C),
]

CHANGE_TYPE = "New Provision"
DETECTED_BY = "manual-seed:gazette-import"
CONFIDENCE = 0.97


def make_anchor(provision_id: str) -> str:
    """Word bookmark names: letters/digits/underscores only, must start with a letter."""
    anchor = re.sub(r"[^A-Za-z0-9_]", "_", provision_id)
    if not anchor[0].isalpha():
        anchor = "P_" + anchor
    return anchor[:40]


def build_provision_row(pid, ref, topic, summary, eff_group, full_text, idx):
    eff_date, eff_note = eff_group
    change_id = f"CHG-A{idx:04d}"
    instrument_type = "Schedule" if ref.startswith("Schedule") else "Act Section"
    return {
        "provision_id": pid,
        "instrument_type": instrument_type,
        "reference": ref,
        "topic_category": topic,
        "current_summary": summary,
        "full_text": full_text,
        "full_text_path": DOCX_PATH,
        "full_text_anchor": make_anchor(pid),
        "sort_order": idx,
        "status": "Active",
        "effective_date": eff_date,
        "last_updated_date": FETCHED_DATE,
        "source_document": ACT_SOURCE_DOC,
        "source_url": ACT_SOURCE_URL,
        "confidence_score": CONFIDENCE,
        "review_status": "Pending Review",
        "reviewed_by": None,
        "review_date": None,
        "latest_change_id": change_id,
        "notes": eff_note if eff_date > FETCHED_DATE else "Currently in force.",
    }, change_id, eff_note


def build_change_row(change_id, pid, summary, full_text, eff_note):
    return {
        "change_id": change_id,
        "detected_timestamp": f"{FETCHED_DATE} 00:00",
        "provision_id": pid,
        "change_type": CHANGE_TYPE,
        "old_value_summary": None,
        "new_value_summary": summary,
        "old_full_text": None,
        "new_full_text": full_text,
        "source_document": ACT_SOURCE_DOC,
        "source_url": ACT_SOURCE_URL,
        "detected_by": DETECTED_BY,
        "confidence_score": CONFIDENCE,
        "review_status": "Pending Review",
        "reviewed_by": None,
        "review_date": None,
        "applied_to_master": "Y",
        "notes": f"Initial baseline load from Act text; commencement per G.S.R. 843(E). {eff_note}",
    }


def main(db_path=None):
    """db_path: optional override, for tests — seeds a scratch database
    instead of the real db/dpdpa.db. Defaults to the real one."""
    if db_path is None:
        db_path = PROJECT_ROOT / "db" / "dpdpa.db"
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = get_connection(db_path)
    init_schema(conn)

    verbatim_full_text = load_verbatim_full_text()

    prov_cols = None
    change_cols = None
    n = 0

    for i, (pid, ref, topic, summary, eff_group) in enumerate(PROVISIONS, start=1):
        full_text = verbatim_full_text[pid]
        prov_row, change_id, eff_note = build_provision_row(pid, ref, topic, summary, eff_group, full_text, i)
        change_row = build_change_row(change_id, pid, summary, full_text, eff_note)

        if prov_cols is None:
            prov_cols = list(prov_row.keys())
        if change_cols is None:
            change_cols = list(change_row.keys())

        conn.execute(
            f"INSERT OR REPLACE INTO provisions ({','.join(prov_cols)}) "
            f"VALUES ({','.join('?' for _ in prov_cols)})",
            [prov_row[c] for c in prov_cols],
        )
        conn.execute(
            f"INSERT OR REPLACE INTO change_log ({','.join(change_cols)}) "
            f"VALUES ({','.join('?' for _ in change_cols)})",
            [change_row[c] for c in change_cols],
        )
        n += 1

    source_rows = [
        {
            "document_id": "SRC-0002",
            "source": "MeitY",
            "title": ACT_SOURCE_DOC,
            "url": ACT_SOURCE_URL,
            "published_date": "2023-08-11",
            "fetched_date": FETCHED_DATE,
            "content_hash": "manual-seed-not-hashed",
            "processing_status": "Processed",
            "linked_change_ids": ",".join(f"CHG-A{i:04d}" for i in range(1, n + 1)),
        },
        {
            "document_id": "SRC-0003",
            "source": "eGazette",
            "title": COMMENCEMENT_SOURCE_DOC,
            "url": COMMENCEMENT_SOURCE_URL,
            "published_date": "2025-11-13",
            "fetched_date": FETCHED_DATE,
            "content_hash": "manual-seed-not-hashed",
            "processing_status": "Processed",
            "linked_change_ids": ",".join(f"CHG-A{i:04d}" for i in range(1, n + 1)),
        },
    ]
    for source_row in source_rows:
        conn.execute(
            f"INSERT OR REPLACE INTO source_log ({','.join(source_row)}) "
            f"VALUES ({','.join('?' for _ in source_row)})",
            list(source_row.values()),
        )

    conn.commit()
    conn.close()
    print(f"Loaded {n} Act provisions (full_text verbatim from {VERBATIM_JSON_PATH.name}) "
          f"and {n} change_log rows.")


if __name__ == "__main__":
    main()
